# Generated by Django 4.2.11 on 2026-04-02 03:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(help_text='Deskripsi atau caption untuk gambar', max_length=200)),
                ('image', models.ImageField(help_text='File gambar (max 5MB)', upload_to='images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Ukuran file dalam bytes', null=True)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Lebar gambar dalam pixel', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Tinggi gambar dalam pixel', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Tanggal dan waktu upload')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Tanggal dan waktu update terakhir')),
                ('is_active', models.BooleanField(default=True, help_text='Status aktif/tidak aktif gambar')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['-uploaded_at'], name='image_image_uploade_b0dd4b_idx'), models.Index(fields=['is_active', '-uploaded_at'], name='image_image_is_acti_5162fe_idx')],
            },
        ),
    ]
